#!/bin/bash
#This file have to be in the same path that file Release

[[ $# -eq 0 ]] && {
  your_key_id=Ivam3
} || {
  your_key_id=$1
}

#Generate key
gpg --full-generate-key
#Export key 
gpg --armor --export $your_key_id > public_key.gpg
#Confirm if it exist
gpg --list-keys
#Sign Release file
gpg --default-key $your_key_id -abs -o Release.gpg Release
gpg --default-key $your_key_id --clearsign -o InRelease Release

echo """
Dont forget download the key in users device :

curl -fsSL "https://raw.githubusercontent.com/ivam3/termux-packages/gh-pages/dists/stable/public_key.gpg" | \
  gpg --dearmor|tee "$PREFIX/etc/apt/trusted.gpg.d/ivam3.gpg" >/dev/null && apt update

"""

