#!/bin/bash
#This file have to be in the same path that file Release
your_key_id="Ivam3"

usage(){
  echo -en """usage: $0 [option] [argument]\n\nOPTIONS |  ARGUMENT  |  DESCRIPTION\n h\t\t\t Run this menu\n u\t     id_name\t GPG signed identificator\n a\t   sign|create\t sign=to sign files\n\t\t\t create=to create a new gpg key\n"""
   exit 1
}

[[ $# -eq 0 ]] && { usage; }
while getopts g:a:u:h opts; do
  case $opts in
    h|*) usage ;;
    u) your_key_id=$OPTARG ;;
    a) action=$OPTARG ;;
  esac
done 

[[ $actions = create ]] && {
  #Generate key
  gpg --full-generate-key
  #Export key 
  gpg --armor --export $your_key_id > public_key.gpg
  #Confirm if it exist
  gpg --list-keys
}

#Sign Release file
gpg --default-key $your_key_id -abs -o Release.gpg Release
gpg --default-key $your_key_id --clearsign -o InRelease Release

echo """
[W]: Dont forget download the key in users device :

curl -fsSL "https://raw.githubusercontent.com/ivam3/termux-packages/gh-pages/dists/stable/public_key.gpg"|gpg --dearmor|tee "\$PREFIX/etc/apt/trusted.gpg.d/ivam3.gpg" >/dev/null && apt update
"""

