#!/bin/bash
#Origin: Termux
#Label: Termux
#Suite: stable
#Codename: stable
#Architectures: aarch64
#Components: extras
#Description: Termux packages
#Date: $(date -R)
Pkgs=$(find extras -type f -name "Packages")
for i in $Pkgs;do
  for t in MD5Sum SHA1 SHA256 SHA512;do
    echo """$t:
     $(md5sum $i | awk '{ print $1}') $(stat --format=%s $i) $(md5sum $i | awk '{ print $2 }')
     $(md5sum $i.xz | awk '{ print $1 }') $(stat --format=%s $i.xz) $(md5sum $i | awk '{ print $2 }')"""
  done
done
