# kitty — Termux:X11
font_family Hack Nerd Font Mono
bold_font auto
italic_font auto
bold_italic_font auto
font_size 15.0
background #1a1b26
foreground #c0caf5
background_opacity 0.92
dynamic_background_opacity yes
cursor #7aa2f7
cursor_shape beam
selection_background #33467c
selection_foreground #c0caf5
scrollback_lines 5000
copy_on_select yes
strip_trailing_spaces smart
confirm_os_window_close 0
window_padding_width 4
hide_window_decorations yes
enable_audio_bell no
update_check_interval 0
clipboard_control write-clipboard write-primary read-clipboard read-primary
